apiVersion: apps/v1
kind: Deployment
metadata:
  name: dongtai-mysql
  namespace: iast-test
  annotations:
    kubesphere.io/description: dongtai-mysql
  labels:
    app: dongtai-mysql
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dongtai-mysql
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: dongtai-mysql
        version: v1
    spec:
      containers:
        - name: dongtai-mysql-container
          image: registry.cn-hongkong.aliyuncs.com/huoxian_pub/dongtai-mysql-unittest:VERSION
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash","-c", "sleep 30; cat /tmp/poststart.sql | mysql -uroot -p'dongtai-iast' --default-character-set=utf8mb4 dongtai_webapi"]
          resources:
            limits:
              cpu: "1000m"
              memory: 1000Mi
            requests:
              cpu: "500m"
              memory: 1000Mi
          ports:
          - containerPort: 3306
            protocol: TCP
            name: tcp-mysql
          livenessProbe:
            failureThreshold: 1
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 40
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /tmp/poststart.sql
            subPath: poststart.sql
            name: hookvolume
      volumes:
      - name: hookvolume
        configMap:
          name: poststarthook
          defaultMode: 0755
      imagePullSecrets:
        - name: aliyun-registry-secret